version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.sh
    volumes:
      - ./:/app/
    ports:
      - "8080:8000"
    command: "python manage.py runserver 0.0.0.0:8000"
