apiVersion: v1
kind: Pod
metadata:
  name: pod-noschedule
spec:
  nodeName: minikube
  containers:
    - name: nginx-cont
      image: nginx:alpine
  tolerations:
    - key: node-group
      operator: Equal
      value: staging
      effect: NoSchedule
