apiVersion: v1
kind: Pod
metadata:
  name: pod-with-node-affinity
  namespace: staging
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-group
                operator: In
                values:
                  - staging

  containers:
    - name: nginx-cont
      image: nginx:alpine
  tolerations:
    - key: node-group
      operator: Equal
      value: staging
      effect: NoSchedule
