name: Build image

on:
  push:
    branches:
      - master
    path-ignore:
      - '**/README.md'
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to the ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version
        id: version
        run: |
          if ${{ contains(github.ref, 'master') }}; then
            VERSION=development-${GITHUB_SHA::8}-$(date +%s)
          fi
          if ${{ github.event.action == 'published' }}; then
            VERSION=${GITHUB_REF/refs\/tags\//}
          fi
          echo ::set-output name=VERSION::${VERSION}

      - name: Extract metadata (tag, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:v0.11.0

      - name: Build and publish image
        id: build_image
        uses: docker/build-push-action@v4

        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: ${{ steps.meta.outputs.labels }}
