name: My-workflows

on:
  push:
    branches:
      - feature/POD-19

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: false
        tags: django_test:latest

    - name: Test
      run: python manage.py test
    - name: Flake8 Check
      run: |
        poetry add flake8
        flake8 --exclude=migrations --max-line-length=120 .

